settings:
  debug: false
  prefix: "<white>[ <yellow>STC</yellow> ]"

default_toggle_item:
  all: false
  per: false

toggle:
  coal:
    display: "<gray>AutoCraft Coal"
    command:
      register: true
      alias: coalcrafttoggle
    item: MMOITEMS;MATERIAL;COAL_CRAFT
    contain:
      - VANILLA;COAL;1
      - MMOITEMS;MATERIAL;COAL;1
      - MMOITEMS;MATERIAL;COAL_ORE;1
      - MMOITEMS;MATERIAL;COAL_BLOCK;1

craft:
  VANILLA;COAL;1:
    ingredient:
      - VANILLA;COAL_ORE;1
  MMOITEMS;MATERIAL;COAL;1:
    ingredient:
      - VANILLA;COAL;64
  MMOITEMS;MATERIAL;COAL_ORE;1:
    ingredient:
      - MMOITEMS;MATERIAL;COAL;64
  MMOITEMS;MATERIAL;COAL_BLOCK;1:
    ingredient:
      - MMOITEMS;MATERIAL;COAL_ORE;64