settings:
  debug: false
  prefix: "<white>[ <yellow>STC</yellow> ]"

default_toggle_item:
  all: false
  per: false

toggle:
  coal: #permission for player can use command is stc.toggle.coal
    display: "<gray>AutoCraft Coal"
    command: #If you don't want to use command for this, you can delete this
      register: true #If true -> after restart player can tab this command, else still can use command but can't tab
      alias: coalcrafttoggle #command
    item: MMOITEMS;MATERIAL;COAL_CRAFT #When this item is in player inventory -> Auto crafting is enable
    contain:
      - VANILLA;COAL;1
      - MMOITEMS;MATERIAL;COAL;1
      - MMOITEMS;MATERIAL;COAL_ORE;1
      - MMOITEMS;MATERIAL;COAL_BLOCK;1

craft:
  # Custom item:
  # ItemsAdder: ITEMSADDER;CUSTOM_ID;AMOUNT
  # Oraxen: ORAXEN;CUSTOM_ID;AMOUNT
  # MMOItems: MMOITEMS;TYPE;ID;AMOUNT
  # ExecutableItems: EXECUTABLEITEMS;ID;AMOUNT
  # Vanilla: VANILLA;TYPE;AMOUNT
  VANILLA;COAL;1:
    ingredient:
      - VANILLA;COAL_ORE;1 #1 coal_ore -> 1 coal
  MMOITEMS;MATERIAL;COAL;1:
    ingredient:
      - VANILLA;COAL;64 #64 vanilla coal -> 1 mmoitems custom coal
  MMOITEMS;MATERIAL;COAL_ORE;1:
    ingredient:
      - MMOITEMS;MATERIAL;COAL;64
  MMOITEMS;MATERIAL;COAL_BLOCK;1:
    ingredient:
      - MMOITEMS;MATERIAL;COAL_ORE;64