name: StackCraft
version: '${project.version}'
main: net.danh.stackcraft.StackCraft
api-version: '1.13'
authors: [ VoChiDanh ]
softdepend:
  - MMOItems
  - MythicLib
  - ItemsAdder
  - Oraxen
  - ExecutableItems
  - SCore
  - Nexo
  - MythicMobs
  - PlaceholderAPI
commands:
  stc:
    description: StackCraft CMD
permissions:
  stc.admin:
    description: Admin Permission
  stc.toggle:
    description: Toggle Command Permission
