name: StackCraft
version: '${version}'
main: net.danh.stackcraft.StackCraft
api-version: '1.16'
folia-supported: true
authors: [ VoChiDanh ]
website: https://sincerpg.github.io/StackCraft/
softdepend:
  - MMOItems
  - MythicLib
  - ItemsAdder
  - Oraxen
  - ExecutableItems
  - SCore
  - Nexo
  - MythicMobs
  - PlaceholderAPI
commands:
  stc:
    description: StackCraft CMD
permissions:
  stc.admin:
    description: Admin Permission
  stc.toggle:
    description: Toggle Command Permission
